### ISSUE TITLE
conf-libpcre overrides break @opam/pcre

### ISSUE THREAD

**Issue by despairblue** [esy-ocaml/esy-opam-override#74]
I have a project that uses @opam/pcre. The last time I upgraded esy pulled in a new version of the override for @conf-libpcre. The entry in the `esy.lock/index.json` changed from

```
    "@opam/conf-libpcre@opam:1@3271fa7f": {
      "id": "@opam/conf-libpcre@opam:1@3271fa7f",
      "name": "@opam/conf-libpcre",
      "version": "opam:1",
      "source": {
        "type": "install",
        "source": [ "no-source:" ],
        "opam": {
          "name": "conf-libpcre",
          "version": "1",
          "path": "esy.lock/opam/conf-libpcre.1"
        }
      },
      "overrides": [],
      "dependencies": [
        "@opam/conf-pkg-config@opam:1.1@67c69c0c",
        "@esy-ocaml/substs@0.0.1@d41d8cd9"
      ],
      "devDependencies": []
    },
```

to

```
    "@opam/conf-libpcre@opam:1@e16abcd7": {
      "id": "@opam/conf-libpcre@opam:1@e16abcd7",
      "name": "@opam/conf-libpcre",
      "version": "opam:1",
      "source": {
        "type": "install",
        "source": [ "no-source:" ],
        "opam": {
          "name": "conf-libpcre",
          "version": "1",
          "path": "esy.lock/opam/conf-libpcre.1"
        }
      },
      "overrides": [
        {
          "opamoverride":
            "esy.lock/overrides/opam__s__conf_libpcre_opam__c__1_opam_override"
        }
      ],
      "dependencies": [
        "esy-pcre@github:esy-packages/esy-pcre#c5076c8facbebaf5f5718c0e270418fd218add7e@d41d8cd9",
        "@opam/conf-pkg-config@opam:1.3@93481236",
        "@esy-ocaml/substs@0.0.1@d41d8cd9"
      ],
      "devDependencies": []
    },
```

See the additional dependency.

That leads to the executable failing to start if the system does not have `libpcre.so.1` in the `LD_LIBRARY_PATH`, like any debian and ubuntu system (they have `libpcre.so.3` installed).\

I think the executable should pick up `esy-pcre` but it does not for some reason.

I made a repro repo: https://github.com/despairblue/esy-pcre-example

This is the commit that likely broke the builds: https://github.com/esy-ocaml/esy-opam-override/commit/5147ed0bcc1134421f1350cc4e6ebc5c1f1e9a6d

cc @ManasJayanth 

---

Side note: I'm still looking for a way to financially support the esy development. I think it was brought up multiple times on discord. I wonder if anybody who's active in the esy ecosystem can be supported via github sponsors?

**Comment by ManasJayanth** [comment]
The overrides are not the cause of the issue here. The following worked

```json
{
  "name": "scamaybe",
  "version": "0.1.0",
  "description": "Example Reason Esy Project",
  "license": "UNLICENSED",
  "esy": {
    "build": "refmterr dune build",
    "buildsInSource": "_build",
    "install": [
      "esy-installer #{self.name}.install"
    ],
    "NOTE": "Optional release Section. Customizes result of `esy release`",
    "release": {
      "bin": [
        "Server"
      ]
    },
    "exportedEnv": {
      "LD_LIBRARY_PATH": {
        "val": "#{esy-pcre.lib : $LD_LIBRARY_PATH }",
        "scope": "global"
      }
    }
  },
  "scripts": {},
  "dependencies": {
    "@esy-ocaml/reason": "3.5.0",
    "@opam/dune": "1.9.3",
    "@opam/pcre": "7.4.1",
    "@opam/conf-libpcre": "1",
    "esy-pcre": "esy-packages/esy-pcre",
    "ocaml": "4.6.10",
    "refmterr": "3.1.10"
  },
  "devDependencies": {
    "@opam/merlin": "3.2.2",
    "ocaml": "4.6.10"
  }
}
```

>  I'm still looking for a way to financially support the esy development...

I really appreciate this. I'm active (as much as I can) but Github sponsors isn't available in India. There are other options like Patreon, but I haven't worked out things need accept financial support from the community - connecting my bank account with such platforms isn't, but coming up with a dedicated and consist plan (roadmaps etc) to contribute to the projects is a little tricky.

But this could be temporary. I will continue talking to other contributors and figure setting up a collective so that we can sustain development efforts at esy.

Your interest is really appreciated ❤

**Comment by despairblue** [comment]
> The overrides are not the cause of the issue here. The following worked

Right, I missed another change in the lock file:

`"@opam/conf-pkg-config@opam:1.1@67c69c0c",`
`"@opam/conf-pkg-config@opam:1.3@93481236"`

The version changed from 1.1 to 1.3. Doing this also fixed the problem:

```
  "resolutions": {
    "@opam/conf-pkg-config": "1.1"
  }
```

Sorry for the stir up ^^

But I think I stick to the newer version with exporting the config. Upside may be that I don't need to install pcre in the production docker image and the build becomes more resilient when upgrading the docker image itself.

> But this could be temporary. I will continue talking to other contributors and figure setting up a collective so that we can sustain development efforts at esy.

Let me know when something changes. I'm not talking about big sums, but regular small ones, I think consistency helps more than throwing 200$ over the fence and then forgetting about it.
